# Generated by Django 5.0 on 2024-02-13 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Branch', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Returned_Foot_Wear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='unit_price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='total_price')),
                ('date_of_purchase', models.DateField(verbose_name='date_of_purchase')),
                ('date_of_return', models.DateTimeField(verbose_name='date_of_return')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_foot_wear_branch', to='Branch.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_foot_wear_product_type', to='Product.foot_wear', verbose_name='foot_wear')),
                ('size_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_foot_wear_size_instance', to='Product.size', verbose_name='size_instance')),
            ],
            options={
                'verbose_name': 'Returned_Foot_Wear',
                'verbose_name_plural': 'Returned_Foot_Wears',
            },
        ),
        migrations.CreateModel(
            name='Returned_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='unit_price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='total_price')),
                ('date_of_purchase', models.DateField(verbose_name='date_of_purchase')),
                ('date_of_return', models.DateTimeField(verbose_name='date_of_return')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_product_branch', to='Branch.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_product_product_type', to='Product.product')),
                ('size_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_product_size_instance', to='Product.size', verbose_name='size_instance')),
            ],
            options={
                'verbose_name': 'Returned_Product',
                'verbose_name_plural': 'Returned_Products',
            },
        ),
        migrations.CreateModel(
            name='Returned_Suit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='unit_price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='total_price')),
                ('date_of_purchase', models.DateField(verbose_name='date_of_purchase')),
                ('date_of_return', models.DateTimeField(verbose_name='date_of_return')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Returned_Suit_branch', to='Branch.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Returned_Suit_product_type', to='Product.suit', verbose_name='suit')),
                ('size_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Returned_Suit_size_instance', to='Product.size', verbose_name='size_instance')),
            ],
            options={
                'verbose_name': 'Returned_Suit',
                'verbose_name_plural': 'Returned_Suits',
            },
        ),
        migrations.CreateModel(
            name='Returned_Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='unit_price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='total_price')),
                ('date_of_purchase', models.DateField(verbose_name='date_of_purchase')),
                ('date_of_return', models.DateTimeField(verbose_name='date_of_return')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Returned_Top_branch', to='Branch.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Returned_Top_product_type', to='Product.top', verbose_name='top')),
                ('size_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Returned_Top_size_instance', to='Product.size', verbose_name='size_instance')),
            ],
            options={
                'verbose_name': 'Returned_Top',
                'verbose_name_plural': 'Returned_Tops',
            },
        ),
    ]
