# Generated by Django 5.0 on 2024-01-15 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0005_branch_foot_wear_foot_wear_size'),
        ('Product', '0002_alter_product_type_p_group_foot_wear'),
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foot_Wear_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foot_wear_stock_branch', to='Branch.branch', verbose_name='branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foot_wear_stock', to='Product.foot_wear', verbose_name='foot_wear')),
                ('size_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foot_wear_stock_size_instance', to='Product.size', verbose_name='size_instance')),
            ],
            options={
                'verbose_name': 'Foot_Wear_Stock',
                'verbose_name_plural': 'Foot_Wear_Stocks',
            },
        ),
    ]
