# Generated by Django 5.0.8 on 2024-08-22 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Category')),
                ('image', models.ImageField(blank=True, default='suits2.jpg', null=True, upload_to='', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('p_group', models.CharField(choices=[('suits', 'suits'), ('foot_wear', 'foot_wear'), ('top', 'top'), ('product', 'product')], default='product', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='Product.category')),
            ],
            options={
                'verbose_name': 'Product_Type',
                'verbose_name_plural': 'Product_Types',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=150, verbose_name='size')),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('unisex', 'unisex')], default='unisex', max_length=6)),
                ('age_group', models.CharField(choices=[('adult', 'adult'), ('children', 'children')], default='adult', max_length=8)),
                ('price', models.IntegerField(verbose_name='price')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_product_type', to='Product.product_type')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='color')),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('unisex', 'unisex')], default='unisex', max_length=6)),
                ('age_group', models.CharField(choices=[('adult', 'adult'), ('children', 'children')], default='adult', max_length=8)),
                ('type', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='type')),
                ('brand', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='brand')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('publish', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='trousers.jpg', null=True, upload_to='', verbose_name='image')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='Product.product_type')),
                ('sizes', models.ManyToManyField(blank=True, related_name='product_sizes', to='Product.size', verbose_name='sizes')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-date', 'product_type'],
            },
        ),
        migrations.CreateModel(
            name='Foot_Wear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='color')),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('unisex', 'unisex')], default='unisex', max_length=6)),
                ('age_group', models.CharField(choices=[('adult', 'adult'), ('children', 'children')], default='adult', max_length=8)),
                ('type', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='type')),
                ('brand', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='brand')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('publish', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='shoes.jpg', null=True, upload_to='', verbose_name='image')),
                ('sole_color', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Sole Color')),
                ('binding', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='binding')),
                ('body_design', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='body_design')),
                ('top_design', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='top_design')),
                ('sole_type', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='sole_type')),
                ('stock', models.CharField(blank=True, default=None, max_length=5, null=True, verbose_name='brand')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foot_wear_product_type', to='Product.product_type')),
                ('sizes', models.ManyToManyField(blank=True, related_name='foot_wear_sizes', to='Product.size', verbose_name='sizes')),
            ],
            options={
                'verbose_name': 'Foot_Wear',
                'verbose_name_plural': 'Foot_Wears',
                'ordering': ['-date', 'product_type'],
            },
        ),
        migrations.CreateModel(
            name='Suit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='color')),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('unisex', 'unisex')], default='unisex', max_length=6)),
                ('age_group', models.CharField(choices=[('adult', 'adult'), ('children', 'children')], default='adult', max_length=8)),
                ('type', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='type')),
                ('brand', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='brand')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('publish', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='suits.jpg', null=True, upload_to='', verbose_name='image')),
                ('sleeve', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='sleeve')),
                ('breasted', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='breasted')),
                ('button', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='button')),
                ('pcs', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='pcs')),
                ('golden_button', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='golden button')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suit_product_type', to='Product.product_type')),
                ('sizes', models.ManyToManyField(blank=True, related_name='sizes', to='Product.size', verbose_name='sizes')),
            ],
            options={
                'verbose_name': 'Suit',
                'verbose_name_plural': 'Suits',
                'ordering': ['-date', 'product_type'],
            },
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='color')),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('unisex', 'unisex')], default='unisex', max_length=6)),
                ('age_group', models.CharField(choices=[('adult', 'adult'), ('children', 'children')], default='adult', max_length=8)),
                ('type', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='type')),
                ('brand', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='brand')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('publish', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='shirts.jpg', null=True, upload_to='', verbose_name='image')),
                ('sleeve', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='sleeve')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_product_type', to='Product.product_type')),
                ('sizes', models.ManyToManyField(blank=True, related_name='top_sizes', to='Product.size', verbose_name='sizes')),
            ],
            options={
                'verbose_name': 'Top',
                'verbose_name_plural': 'Tops',
                'ordering': ['-date', 'product_type'],
            },
        ),
    ]
