# Generated by Django 5.0 on 2024-01-08 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Category')),
                ('image', models.ImageField(blank=True, default='image', null=True, upload_to='', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('p_group', models.CharField(choices=[('suits', 'suits'), ('foot_wears', 'foot_wears'), ('top', 'top'), ('product', 'product')], default='product', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='Product.category')),
            ],
            options={
                'verbose_name': 'Product_Type',
                'verbose_name_plural': 'Product_Types',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=150, verbose_name='size')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unisex')], default='U', max_length=2)),
                ('age_group', models.CharField(choices=[('A', 'Adult'), ('C', 'Children')], default='A', max_length=2)),
                ('price', models.IntegerField(verbose_name='price')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_product_type', to='Product.product_type')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=150, verbose_name='description')),
                ('color', models.CharField(max_length=200, verbose_name='color')),
                ('image', models.ImageField(blank=True, default='image', null=True, upload_to='', verbose_name='image')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unisex')], default='U', max_length=2)),
                ('age_group', models.CharField(choices=[('A', 'Adult'), ('C', 'Children')], default='A', max_length=2)),
                ('brand', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='brand')),
                ('type', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='type')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('publish', models.BooleanField(default=False)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='Product.product_type')),
                ('sizes', models.ManyToManyField(blank=True, related_name='product_sizes', to='Product.size', verbose_name='sizes')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Suit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=150, verbose_name='description')),
                ('color', models.CharField(max_length=200, verbose_name='color')),
                ('image', models.ImageField(blank=True, default='image', null=True, upload_to='', verbose_name='image')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unisex')], default='U', max_length=2)),
                ('age_group', models.CharField(choices=[('A', 'Adult'), ('C', 'Children')], default='A', max_length=2)),
                ('brand', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='brand')),
                ('type', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='type')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('publish', models.BooleanField(default=False)),
                ('breasted', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='breasted')),
                ('button', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='button')),
                ('pics', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='pics')),
                ('golden_button', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='golden button')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suit_product_type', to='Product.product_type')),
                ('sizes', models.ManyToManyField(blank=True, related_name='sizes', to='Product.size', verbose_name='sizes')),
            ],
            options={
                'verbose_name': 'Suit',
                'verbose_name_plural': 'Suits',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=150, verbose_name='description')),
                ('color', models.CharField(max_length=200, verbose_name='color')),
                ('image', models.ImageField(blank=True, default='image', null=True, upload_to='', verbose_name='image')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unisex')], default='U', max_length=2)),
                ('age_group', models.CharField(choices=[('A', 'Adult'), ('C', 'Children')], default='A', max_length=2)),
                ('brand', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='brand')),
                ('type', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='type')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('publish', models.BooleanField(default=False)),
                ('sleeves', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='sleeves')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_product_type', to='Product.product_type')),
                ('sizes', models.ManyToManyField(blank=True, related_name='top_sizes', to='Product.size', verbose_name='sizes')),
            ],
            options={
                'verbose_name': 'Top',
                'verbose_name_plural': 'Tops',
                'ordering': ['-date'],
            },
        ),
    ]
