# Generated by Django 5.0.2 on 2024-02-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foot_wear',
            options={'ordering': ['-date', 'product_type'], 'verbose_name': 'Foot_Wear', 'verbose_name_plural': 'Foot_Wears'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date', 'product_type'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='suit',
            options={'ordering': ['-date', 'product_type'], 'verbose_name': 'Suit', 'verbose_name_plural': 'Suits'},
        ),
        migrations.AlterModelOptions(
            name='top',
            options={'ordering': ['-date', 'product_type'], 'verbose_name': 'Top', 'verbose_name_plural': 'Tops'},
        ),
    ]
