# Generated by Django 5.0 on 2024-01-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_type_p_group_foot_wear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foot_wear',
            name='color',
            field=models.CharField(max_length=50, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='foot_wear',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=50, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='suit',
            name='color',
            field=models.CharField(max_length=50, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='suit',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='top',
            name='color',
            field=models.CharField(max_length=50, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='top',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='type'),
        ),
    ]
