# Generated by Django 5.0.2 on 2024-08-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_foot_wear_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top',
            name='sleeves',
        ),
        migrations.AddField(
            model_name='suit',
            name='sleeve',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='sleeve'),
        ),
        migrations.AddField(
            model_name='top',
            name='sleeve',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='sleeve'),
        ),
    ]
