# Generated by Django 5.0.2 on 2024-08-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_remove_top_sleeves_suit_sleeve_top_sleeve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suit',
            name='pics',
            field=models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='pics'),
        ),
    ]
