# Generated by Django 5.0.2 on 2024-08-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_suit_pics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foot_wear',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='suit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='suit',
            name='pics',
        ),
        migrations.RemoveField(
            model_name='top',
            name='description',
        ),
        migrations.AddField(
            model_name='foot_wear',
            name='binding',
            field=models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='binding'),
        ),
        migrations.AddField(
            model_name='foot_wear',
            name='body_design',
            field=models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='body_design'),
        ),
        migrations.AddField(
            model_name='foot_wear',
            name='sole_type',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='sole_type'),
        ),
        migrations.AddField(
            model_name='foot_wear',
            name='stock',
            field=models.CharField(blank=True, default=None, max_length=5, null=True, verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='foot_wear',
            name='top_design',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='top_design'),
        ),
        migrations.AddField(
            model_name='suit',
            name='pcs',
            field=models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='pcs'),
        ),
        migrations.AlterField(
            model_name='foot_wear',
            name='brand',
            field=models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='foot_wear',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='suit',
            name='brand',
            field=models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='suit',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='top',
            name='brand',
            field=models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='top',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='type'),
        ),
    ]
