# Generated by Django 5.0.2 on 2024-08-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_remove_foot_wear_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foot_wear',
            name='image',
            field=models.ImageField(blank=True, default='shoes.webp', null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='trousers.webp', null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='suit',
            name='image',
            field=models.ImageField(blank=True, default='suits.jpg', null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='top',
            name='image',
            field=models.ImageField(blank=True, default='shirts.jpg', null=True, upload_to='', verbose_name='image'),
        ),
    ]
