# Generated by Django 5.0.2 on 2024-08-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_foot_wear_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='suits2.jpg', null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='foot_wear',
            name='image',
            field=models.ImageField(blank=True, default='shoes.jpg', null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='trousers.jpg', null=True, upload_to='', verbose_name='image'),
        ),
    ]
