# Generated by Django 5.0.8 on 2024-08-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_alter_category_image_alter_foot_wear_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foot_wear',
            name='age_group',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Children', 'Children')], default='Adult', max_length=8),
        ),
        migrations.AlterField(
            model_name='foot_wear',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Unisex', 'Unisex')], default='Unisex', max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='age_group',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Children', 'Children')], default='Adult', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Unisex', 'Unisex')], default='Unisex', max_length=6),
        ),
        migrations.AlterField(
            model_name='size',
            name='age_group',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Children', 'Children')], default='Adult', max_length=8),
        ),
        migrations.AlterField(
            model_name='size',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Unisex', 'Unisex')], default='Unisex', max_length=6),
        ),
        migrations.AlterField(
            model_name='suit',
            name='age_group',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Children', 'Children')], default='Adult', max_length=8),
        ),
        migrations.AlterField(
            model_name='suit',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Unisex', 'Unisex')], default='Unisex', max_length=6),
        ),
        migrations.AlterField(
            model_name='top',
            name='age_group',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Children', 'Children')], default='Adult', max_length=8),
        ),
        migrations.AlterField(
            model_name='top',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Unisex', 'Unisex')], default='Unisex', max_length=6),
        ),
    ]
