# Generated by Django 5.0.8 on 2024-08-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_foot_wear_age_group_alter_foot_wear_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foot_wear',
            name='age_group',
            field=models.CharField(choices=[('adult', 'adult'), ('children', 'children')], default='adult', max_length=8),
        ),
        migrations.AlterField(
            model_name='foot_wear',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male'), ('unisex', 'unisex')], default='unisex', max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='age_group',
            field=models.CharField(choices=[('adult', 'adult'), ('children', 'children')], default='adult', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male'), ('unisex', 'unisex')], default='unisex', max_length=6),
        ),
        migrations.AlterField(
            model_name='size',
            name='age_group',
            field=models.CharField(choices=[('adult', 'adult'), ('children', 'children')], default='adult', max_length=8),
        ),
        migrations.AlterField(
            model_name='size',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male'), ('unisex', 'unisex')], default='unisex', max_length=6),
        ),
        migrations.AlterField(
            model_name='suit',
            name='age_group',
            field=models.CharField(choices=[('adult', 'adult'), ('children', 'children')], default='adult', max_length=8),
        ),
        migrations.AlterField(
            model_name='suit',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male'), ('unisex', 'unisex')], default='unisex', max_length=6),
        ),
        migrations.AlterField(
            model_name='top',
            name='age_group',
            field=models.CharField(choices=[('adult', 'adult'), ('children', 'children')], default='adult', max_length=8),
        ),
        migrations.AlterField(
            model_name='top',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male'), ('unisex', 'unisex')], default='unisex', max_length=6),
        ),
    ]
