# Generated by Django 5.0 on 2024-01-08 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Branch', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bad_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_product_branch', to='Branch.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_product_product_type', to='Product.product')),
                ('size_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bad_product_size_instance', to='Product.size', verbose_name='size_instance')),
            ],
            options={
                'verbose_name': 'Bad_Product',
                'verbose_name_plural': 'Bad_Products',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Bad_Suit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bad_Suit_branch', to='Branch.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bad_Suit_product_type', to='Product.suit')),
                ('size_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bad_Suit_size_instance', to='Product.size', verbose_name='size_instance')),
            ],
            options={
                'verbose_name': 'Bad_Suit',
                'verbose_name_plural': 'Bad_Suits',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Bad_Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bad_Top_branch', to='Branch.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bad_Top_product_type', to='Product.top')),
                ('size_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bad_Top_size_instance', to='Product.size', verbose_name='size_instance')),
            ],
            options={
                'verbose_name': 'Bad_Top',
                'verbose_name_plural': 'Bad_Tops',
                'ordering': ['-date'],
            },
        ),
    ]
