# Generated by Django 5.0 on 2024-01-15 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bad_Product', '0001_initial'),
        ('Branch', '0005_branch_foot_wear_foot_wear_size'),
        ('Product', '0002_alter_product_type_p_group_foot_wear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bad_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_product_product_type', to='Product.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='bad_suit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bad_Suit_product_type', to='Product.suit', verbose_name='Suit'),
        ),
        migrations.AlterField(
            model_name='bad_top',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bad_Top_product_type', to='Product.top', verbose_name='top'),
        ),
        migrations.CreateModel(
            name='Bad_Foot_Wear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_foot_wear_branch', to='Branch.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_foot_wear_product_type', to='Product.foot_wear', verbose_name='foot_wear')),
                ('size_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bad_foot_wear_size_instance', to='Product.size', verbose_name='size_instance')),
            ],
            options={
                'verbose_name': 'Bad_foot_wear',
                'verbose_name_plural': 'Bad_foot_wears',
                'ordering': ['-date'],
            },
        ),
    ]
