# Generated by Django 5.0 on 2024-01-10 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Branch', '0001_initial'),
        ('Sales', '0002_alter_items_p_group_alter_sales_payment_method'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total_amount')),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='expected_amount')),
                ('remark', models.CharField(max_length=200, verbose_name='remark')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('purchase_id', models.CharField(max_length=150, verbose_name='purchase_id')),
                ('total_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total_payment')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='balance')),
                ('fully_paid', models.BooleanField(default=False, verbose_name='fully_paid')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_sale_branch', to='Branch.branch', verbose_name='branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_sale_customer', to='User.customer', verbose_name='customer')),
                ('items', models.ManyToManyField(related_name='credit_sale_Items', to='Sales.items', verbose_name='items')),
            ],
            options={
                'verbose_name': 'Credit_Sale',
                'verbose_name_plural': 'Credit_Sales',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('credit_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_credit_sale', to='Credit_Sales.credit_sale', verbose_name='credit_sale')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
