# Generated by Django 5.0 on 2024-02-13 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Credit_Sales', '0001_initial'),
        ('Sales', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_sale_customer', to='User.customer', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='credit_sale',
            name='items',
            field=models.ManyToManyField(related_name='credit_sale_Items', to='Sales.items', verbose_name='items'),
        ),
        migrations.AddField(
            model_name='payment',
            name='credit_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_credit_sale', to='Credit_Sales.credit_sale', verbose_name='credit_sale'),
        ),
    ]
