# Generated by Django 5.0 on 2024-02-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credit_Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_sale',
            name='purchase_id',
            field=models.CharField(max_length=150, unique=True, verbose_name='purchase_id'),
        ),
    ]
