# Generated by Django 5.0 on 2024-01-12 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_size',
            name='branch_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_product_size', to='Branch.branch_product', verbose_name='branch_product'),
        ),
        migrations.AlterField(
            model_name='suit_size',
            name='branch_suit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_suit_size', to='Branch.branch_suit', verbose_name='Branch_Suit'),
        ),
        migrations.AlterField(
            model_name='suit_size',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_suit_sizes', to='Product.size'),
        ),
        migrations.AlterField(
            model_name='tops_size',
            name='branch_tops',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_tops_size', to='Branch.branch_tops', verbose_name='Branch_Tops'),
        ),
        migrations.AlterField(
            model_name='tops_size',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_tops_sizes', to='Product.size'),
        ),
    ]
