# Generated by Django 5.0 on 2024-01-13 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0003_alter_branch_suit_branch_alter_branch_suit_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_size',
            old_name='branch_product',
            new_name='branch_instance',
        ),
        migrations.RenameField(
            model_name='suit_size',
            old_name='branch_suit',
            new_name='branch_instance',
        ),
        migrations.RenameField(
            model_name='tops_size',
            old_name='branch_tops',
            new_name='branch_instance',
        ),
    ]
