# Generated by Django 5.0 on 2024-01-15 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0004_rename_branch_product_product_size_branch_instance_and_more'),
        ('Product', '0002_alter_product_type_p_group_foot_wear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch_Foot_Wear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_foot_wear_branch', to='Branch.branch', verbose_name='branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_foot_wear_product', to='Product.top', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Branch_Foot_Wear',
                'verbose_name_plural': 'Branch_Foot_Wears',
            },
        ),
        migrations.CreateModel(
            name='Foot_Wear_Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_qty', models.IntegerField(default=0, verbose_name='current_qty')),
                ('returned_qty', models.IntegerField(default=0, verbose_name='returned_qty')),
                ('bad_qty', models.IntegerField(default=0, verbose_name='bad_qty')),
                ('branch_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_foot_wear_size', to='Branch.branch_foot_wear', verbose_name='Branch_foot_wear')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_foot_wear_sizes', to='Product.size')),
            ],
            options={
                'verbose_name': 'Foot_Wear_Size',
                'verbose_name_plural': 'Foot_Wear_Sizes',
            },
        ),
    ]
