# Generated by Django 5.0 on 2024-02-06 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0005_branch_foot_wear_foot_wear_size'),
        ('Product', '0003_alter_foot_wear_color_alter_foot_wear_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_foot_wear',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_foot_wear_product', to='Product.foot_wear', verbose_name='product'),
        ),
    ]
