# Generated by Django 5.0.8 on 2024-08-22 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Branch', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_group', models.CharField(choices=[('suit', 'suit'), ('foot_wear', 'foot_wear'), ('top', 'top'), ('product', 'product')], default='product', max_length=10)),
                ('product_type', models.CharField(max_length=200, verbose_name='product_type')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit_price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total_price')),
                ('mini_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='mini_price')),
                ('expected_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='expected_price')),
                ('foot_wear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_foot_wear', to='Product.foot_wear', verbose_name='foot_wear')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_product', to='Product.product', verbose_name='product')),
                ('size_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_size_instance', to='Product.size', verbose_name='size_instance')),
                ('suit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_suit', to='Product.suit', verbose_name='suit')),
                ('top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_top', to='Product.top', verbose_name='top')),
            ],
            options={
                'verbose_name': 'Items',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total_amount')),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='expected_amount')),
                ('logistics', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='logistics')),
                ('destination', models.CharField(blank=True, default='not set', max_length=256, verbose_name='destination')),
                ('remark', models.CharField(max_length=200, verbose_name='remark')),
                ('channel', models.CharField(choices=[('web', 'web'), ('store', 'store')], default='store', max_length=5, verbose_name='channel')),
                ('payment_method', models.CharField(choices=[('transfer', 'transfer'), ('cash', 'cash'), ('credit', 'credit'), ('on_web', 'on_web')], default='cash', max_length=8, verbose_name='payment_method')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('purchase_id', models.CharField(max_length=150, unique=True, verbose_name='purchase_id')),
                ('paid', models.BooleanField(default=True, verbose_name='paid')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_branch', to='Branch.branch', verbose_name='branch')),
            ],
            options={
                'verbose_name': 'Sales',
                'verbose_name_plural': 'Sales',
                'ordering': ['-date'],
            },
        ),
    ]
