# Generated by Django 5.0 on 2024-01-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='p_group',
            field=models.CharField(choices=[('suit', 'suit'), ('foot_wears', 'foot_wears'), ('top', 'top'), ('product', 'product')], default='product', max_length=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'transfer'), ('cash', 'cash'), ('credit', 'credit'), ('on_web', 'on_web')], default='cash', max_length=8, verbose_name='payment_method'),
        ),
    ]
