# Generated by Django 5.0 on 2024-01-15 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_type_p_group_foot_wear'),
        ('Sales', '0002_alter_items_p_group_alter_sales_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='foot_wear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_foot_wear', to='Product.foot_wear', verbose_name='foot_wear'),
        ),
        migrations.AlterField(
            model_name='items',
            name='p_group',
            field=models.CharField(choices=[('suit', 'suit'), ('foot_wear', 'foot_wear'), ('top', 'top'), ('product', 'product')], default='product', max_length=10),
        ),
    ]
