# Generated by Django 5.0.2 on 2024-02-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='logistics',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='logistics'),
        ),
    ]
