# Generated by Django 5.0.2 on 2024-02-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_items_logistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='logistics',
        ),
    ]
