# Generated by Django 5.0 on 2024-02-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_items_foot_wear_alter_items_p_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='purchase_id',
            field=models.CharField(max_length=150, unique=True, verbose_name='purchase_id'),
        ),
    ]
